# https://cirrus-ci.com/github/burghardt/clamfs
test_task:
  name: FreeBSD test run
  freebsd_instance:
    matrix:
      image_family: freebsd-13-1
      image_family: freebsd-12-3
  env:
    CIRRUS_CLONE_DEPTH: 10
    matrix:
      CLAMFS_SCAN_MODE: fname
      CLAMFS_SCAN_MODE: fdpass
      CLAMFS_SCAN_MODE: stream
  pkginstall_script:
    - pkg install -y devel/autoconf devel/automake devel/pkgconf
    - pkg install -y sysutils/fusefs-libs3 devel/poco devel/boost-libs devel/rlog
  configure_script:
    - sed -i bak -e 's|-Werror ||g' configure.ac
    - sh bootstrap
    - ./configure || { tail -n 500 config.log; false; }
  compile_script:
    - make
  install_script:
    - make install
  configure_clamfs_script:
    - mkdir -p /clamfs/tmp
    - sed 's/clamd.ctl/clamd.sock/g' doc/clamfs.xml | sed "s/fdpass/$CLAMFS_SCAN_MODE/g" > /clamfs/tmp.xml
  dump_clamfs_config_script:
    - cat /clamfs/tmp.xml
  install_clamav_deps_script:
    - cd /usr/ports/security/clamav
    - make all-depends-list | sed 's|/usr/ports/||g' | xargs -rtn1 pkg install -y
  install_clamav_script:
    - cd /usr/ports/security/clamav
    - make -DBATCH install clean
  freshclam_script:
    - freshclam
  start_clamd_script:
    - service clamav-freshclam onestart
    - service clamav-clamd onestart
  load_fuse_script:
    - kldload fuse
  start_clamfs_script:
    - clamfs /clamfs/tmp.xml
  test_empty_script:
    - cd /clamfs/tmp
    - touch empty.file
    - cat empty.file
  test_string_script:
    - cd /clamfs/tmp
    - echo 'Hello World!' > string.txt
    - cat string.txt
  test_eicar_script:
    - cd /clamfs/tmp
    - echo 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' > eicar.com
    - hexdump -C eicar.com || exit 0
