name: drone.io pipeline
kind: pipeline
type: docker
steps:
  - name: build
    image: debian:sid
    commands:
      - apt-get update -qq
      - apt-get install -y build-essential pkg-config autoconf automake
      - apt-get install -y libfuse3-dev libpoco-dev libboost-dev
      - sh autogen.sh
      - sh configure || { tail -n 500 config.log; false; }
      - make
