name: docker workflow

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: ubuntu-devel
        uses: ./.github/actions/build-ubuntu-devel
      - name: ubuntu-latest
        uses: ./.github/actions/build-ubuntu-latest
      - name: ubuntu-rolling
        uses: ./.github/actions/build-ubuntu-rolling
      - name: debian-unstable
        uses: ./.github/actions/build-debian-unstable
      - name: debian-testing
        uses: ./.github/actions/build-debian-testing
      - name: debian-stable
        uses: ./.github/actions/build-debian-stable
      #- name: debian-oldstable
      #  uses: ./.github/actions/build-debian-oldstable
      - name: fedora-rawhide
        uses: ./.github/actions/build-fedora-rawhide
      - name: fedora-latest
        uses: ./.github/actions/build-fedora-latest
