name: docker workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-devel
          - ubuntu-latest
          - ubuntu-rolling
          - debian-unstable
          - debian-testing
          - debian-stable
          - debian-oldstable
          - fedora-rawhide
          - fedora-latest
    name: build on ${{ matrix.image }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ${{ matrix.image }}
        uses: ./.github/actions/build-${{ matrix.image }}
