name: doxygen workflow

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: doxygen
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install \
               build-essential \
               meson ninja-build \
               doxygen graphviz \
               automake \
               pkg-config \
               librlog-dev \
               libpoco-dev \
               libboost-dev \
               libdmalloc-dev
      - name: fuse3
        run: |
          mkdir /tmp/fuse3 ; cd /tmp/fuse3
          git clone --depth 1 https://github.com/libfuse/libfuse.git .
          mkdir build ; cd build
          meson ..
          ninja
          sudo ninja install
      - name: bootstrap
        run: sh bootstrap
      - name: configure
        run: sh configure || { tail -n 500 config.log; false; }
      - name: clean
        run: make clean
      - name: doxygen
        run: make doxygen
